// File: app/cpq-demo/models.ts

import React from 'react';
import {
  FaCode,
  FaFileAlt,
  FaFilePdf,
  FaImage,
  FaVideo,
  FaGithub,
  FaInfoCircle,
  FaDatabase,
  FaTools,
  FaBookOpen,
  FaQuestionCircle,
  FaStar,
  FaLaptopCode,
  FaCogs,
  FaCloud,
  FaNetworkWired,
} from 'react-icons/fa';

export type CPQComponent = {
  id: string;
  name: string;
  unit: string;
  unitLaborCost: number;       // $ per hr
  laborHours: number;          // hrs
  unitMaterialCost: number;    // $ per unit
  quantity: number;            // number of units
  optional: boolean;
  Icon: React.ComponentType<{ className?: string }>;
  laborMarginPercent: number;    // % over labor cost
  materialMarkupPercent: number; // % over material cost
  discountPercent: number;       // % discount on total
};

export const iconOptions: {
  id: string;
  label: string;
  Icon: React.ComponentType<{ className?: string }>;
}[] = [
  { id: 'FaCode', label: 'Code Snippet', Icon: FaCode },
  { id: 'FaFileAlt', label: 'README', Icon: FaFileAlt },
  { id: 'FaFilePdf', label: 'PDF Guide', Icon: FaFilePdf },
  { id: 'FaImage', label: 'Image', Icon: FaImage },
  { id: 'FaVideo', label: 'Video', Icon: FaVideo },
  { id: 'FaGithub', label: 'Repo Access', Icon: FaGithub },
  { id: 'FaInfoCircle', label: 'Description', Icon: FaInfoCircle },
  { id: 'FaDatabase', label: 'Sample Data', Icon: FaDatabase },
  { id: 'FaTools', label: 'Troubleshoot', Icon: FaTools },
  { id: 'FaBookOpen', label: 'Case Study', Icon: FaBookOpen },
  { id: 'FaQuestionCircle', label: 'FAQ', Icon: FaQuestionCircle },
  { id: 'FaStar', label: 'Testimonial', Icon: FaStar },
  { id: 'FaLaptopCode', label: 'Custom .NET', Icon: FaLaptopCode },
  { id: 'FaCogs', label: 'CAD/Automation', Icon: FaCogs },
  { id: 'FaCloud', label: 'Cloud/DevOps', Icon: FaCloud },
  { id: 'FaNetworkWired', label: 'Data/ERP', Icon: FaNetworkWired },
];

export const initialCPQComponents: CPQComponent[] = [
  {
    id: 'snippet',
    name: 'Code Snippet',
    unit: 'per snippet',
    unitLaborCost: 50,
    laborHours: 1,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaCode,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'readme',
    name: 'Instructions (README)',
    unit: 'per document',
    unitLaborCost: 40,
    laborHours: 1.5,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaFileAlt,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'guide',
    name: 'Setup Guide (PDF)',
    unit: 'per guide',
    unitLaborCost: 60,
    laborHours: 2,
    unitMaterialCost: 5,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'productImage',
    name: 'Product Image',
    unit: 'per image',
    unitLaborCost: 30,
    laborHours: 0.5,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaImage,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'previewVideo',
    name: 'Preview Video',
    unit: 'per video',
    unitLaborCost: 80,
    laborHours: 1,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaVideo,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'repo',
    name: 'Temporary Repo Access',
    unit: '7-day access',
    unitLaborCost: 0,
    laborHours: 0,
    unitMaterialCost: 25,
    quantity: 1,
    optional: false,
    Icon: FaGithub,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'productDesc',
    name: 'Product Description',
    unit: 'per product',
    unitLaborCost: 45,
    laborHours: 1,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaInfoCircle,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'sampleData',
    name: 'Sample Data',
    unit: 'per dataset',
    unitLaborCost: 35,
    laborHours: 1,
    unitMaterialCost: 5,
    quantity: 0,
    optional: true,
    Icon: FaDatabase,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'troubleshoot',
    name: 'Troubleshooting Guide',
    unit: 'per guide',
    unitLaborCost: 45,
    laborHours: 1,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaTools,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'caseStudy',
    name: 'Case Study',
    unit: 'per document',
    unitLaborCost: 60,
    laborHours: 2,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaBookOpen,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'faq',
    name: 'FAQ Document',
    unit: 'per document',
    unitLaborCost: 30,
    laborHours: 1,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaQuestionCircle,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'testimonial',
    name: 'Testimonial',
    unit: 'per testimonial',
    unitLaborCost: 20,
    laborHours: 0.5,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaStar,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];

export const medicalComponents: CPQComponent[] = [
  {
    id: 'medBrochure',
    name: 'Patient Education Brochure',
    unit: 'per PDF',
    unitLaborCost: 70,
    laborHours: 2,
    unitMaterialCost: 5,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'medIllustration',
    name: 'Anatomical Diagram',
    unit: 'per image',
    unitLaborCost: 90,
    laborHours: 2.5,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaImage,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'medTutorialVideo',
    name: 'Procedure Tutorial Video',
    unit: 'per video',
    unitLaborCost: 150,
    laborHours: 3,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaVideo,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'medCaseStudy',
    name: 'Clinical Case Study',
    unit: 'per document',
    unitLaborCost: 120,
    laborHours: 3,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaBookOpen,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];

export const energyComponents: CPQComponent[] = [
  {
    id: 'energyReport',
    name: 'Energy Efficiency Report',
    unit: 'per PDF',
    unitLaborCost: 80,
    laborHours: 2,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'solarDiagram',
    name: 'Solar Grid Diagram',
    unit: 'per image',
    unitLaborCost: 50,
    laborHours: 1,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaImage,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'energySimulation',
    name: 'Energy Simulation Data',
    unit: 'per dataset',
    unitLaborCost: 100,
    laborHours: 2,
    unitMaterialCost: 10,
    quantity: 0,
    optional: true,
    Icon: FaDatabase,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];

export const musicAlbumComponents: CPQComponent[] = [
  {
    id: 'albumCover',
    name: 'Album Cover Artwork',
    unit: 'per image',
    unitLaborCost: 40,
    laborHours: 1,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaImage,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'trackPreview',
    name: 'Track Preview Video',
    unit: 'per video',
    unitLaborCost: 70,
    laborHours: 1.5,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaVideo,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'lyricsSheet',
    name: 'Lyrics Sheet',
    unit: 'per PDF',
    unitLaborCost: 30,
    laborHours: 0.5,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];

export const filmComponents: CPQComponent[] = [
  {
    id: 'filmPoster',
    name: 'Film Poster',
    unit: 'per image',
    unitLaborCost: 60,
    laborHours: 1,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaImage,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'trailer',
    name: 'Movie Trailer',
    unit: 'per video',
    unitLaborCost: 150,
    laborHours: 3,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaVideo,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'behindScenes',
    name: 'Behind the Scenes Featurette',
    unit: 'per video',
    unitLaborCost: 120,
    laborHours: 2.5,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaVideo,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];

export const etoCadComponents: CPQComponent[] = [
  {
    id: 'cadDrawing',
    name: 'Custom CAD Drawing',
    unit: 'per file',
    unitLaborCost: 200,
    laborHours: 4,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaCode,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'cadPreview',
    name: '2D Assembly Preview',
    unit: 'per image',
    unitLaborCost: 70,
    laborHours: 1.5,
    unitMaterialCost: 0,
    quantity: 1,
    optional: true,
    Icon: FaImage,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'cadRepoAccess',
    name: 'Project Repo Access',
    unit: '7-day access',
    unitLaborCost: 0,
    laborHours: 0,
    unitMaterialCost: 50,
    quantity: 0,
    optional: true,
    Icon: FaGithub,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];

export const bankingComponents: CPQComponent[] = [
  {
    id: 'statementPDF',
    name: 'Financial Statement PDF',
    unit: 'per document',
    unitLaborCost: 50,
    laborHours: 1,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'trendReport',
    name: 'Banking Trend Analysis Report',
    unit: 'per document',
    unitLaborCost: 100,
    laborHours: 2,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaFileAlt,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'marketDataset',
    name: 'Market Dataset',
    unit: 'per dataset',
    unitLaborCost: 120,
    laborHours: 2,
    unitMaterialCost: 20,
    quantity: 0,
    optional: true,
    Icon: FaDatabase,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];

export const softwareSalesComponents: CPQComponent[] = [
  {
    id: 'productManual',
    name: 'Software Product Manual',
    unit: 'per PDF',
    unitLaborCost: 60,
    laborHours: 1.5,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'promoVideo',
    name: 'Promotional Video',
    unit: 'per video',
    unitLaborCost: 90,
    laborHours: 2,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaVideo,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'trialAccess',
    name: '14-Day Trial Access',
    unit: 'per license',
    unitLaborCost: 0,
    laborHours: 0,
    unitMaterialCost: 25,
    quantity: 1,
    optional: true,
    Icon: FaGithub,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];

export const realEstateComponents: CPQComponent[] = [
  {
    id: 'propertyBrochure',
    name: 'Property Brochure (PDF)',
    unit: 'per PDF',
    unitLaborCost: 80,
    laborHours: 2,
    unitMaterialCost: 5,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'floorPlan',
    name: 'Floor Plan Diagram',
    unit: 'per image',
    unitLaborCost: 120,
    laborHours: 3,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaImage,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'videoTour',
    name: 'Virtual Tour Video',
    unit: 'per video',
    unitLaborCost: 200,
    laborHours: 4,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaVideo,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'marketAnalysis',
    name: 'Market Analysis Report',
    unit: 'per document',
    unitLaborCost: 150,
    laborHours: 3,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaFileAlt,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'siteDataset',
    name: 'Site Performance Data',
    unit: 'per dataset',
    unitLaborCost: 100,
    laborHours: 2,
    unitMaterialCost: 10,
    quantity: 0,
    optional: true,
    Icon: FaDatabase,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'caseStudyRealEstate',
    name: 'Client Success Case Study',
    unit: 'per document',
    unitLaborCost: 130,
    laborHours: 2.5,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaBookOpen,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];

export const constructionComponents: CPQComponent[] = [
  {
    id: 'siteBlueprint',
    name: 'Site Blueprint PDF',
    unit: 'per document',
    unitLaborCost: 150,
    laborHours: 3,
    unitMaterialCost: 10,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'safetyManual',
    name: 'Safety & Compliance Manual',
    unit: 'per PDF',
    unitLaborCost: 120,
    laborHours: 2.5,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaFileAlt,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: '3dRender',
    name: '3D Render Visualization',
    unit: 'per image',
    unitLaborCost: 200,
    laborHours: 4,
    unitMaterialCost: 0,
    quantity: 1,
    optional: true,
    Icon: FaImage,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'equipmentDataset',
    name: 'Equipment Cost Dataset',
    unit: 'per dataset',
    unitLaborCost: 100,
    laborHours: 2,
    unitMaterialCost: 15,
    quantity: 0,
    optional: true,
    Icon: FaDatabase,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];
export const biotechComponents: CPQComponent[] = [
  {
    id: 'labReport',
    name: 'Laboratory Test Report',
    unit: 'per PDF',
    unitLaborCost: 140,
    laborHours: 2.5,
    unitMaterialCost: 5,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'genomeDataset',
    name: 'Genome Analysis Dataset',
    unit: 'per dataset',
    unitLaborCost: 250,
    laborHours: 5,
    unitMaterialCost: 20,
    quantity: 1,
    optional: false,
    Icon: FaDatabase,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'clinicalAnimation',
    name: 'Clinical Procedure Animation',
    unit: 'per video',
    unitLaborCost: 300,
    laborHours: 6,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaVideo,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];
export const automotiveComponents: CPQComponent[] = [
  {
    id: 'vehicleSpecSheet',
    name: 'Vehicle Specification Sheet',
    unit: 'per PDF',
    unitLaborCost: 90,
    laborHours: 1.5,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'cadModel',
    name: 'CAD Component Model',
    unit: 'per file',
    unitLaborCost: 200,
    laborHours: 4,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaCode,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'windTunnelVideo',
    name: 'Wind Tunnel Test Video',
    unit: 'per video',
    unitLaborCost: 250,
    laborHours: 5,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaVideo,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'batteryDataset',
    name: 'Battery Performance Dataset',
    unit: 'per dataset',
    unitLaborCost: 150,
    laborHours: 3,
    unitMaterialCost: 20,
    quantity: 0,
    optional: true,
    Icon: FaDatabase,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];
export const aerospaceComponents: CPQComponent[] = [
  {
    id: 'flightManual',
    name: 'Flight Manual PDF',
    unit: 'per PDF',
    unitLaborCost: 200,
    laborHours: 4,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaFilePdf,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'satelliteImage',
    name: 'Satellite Component Diagram',
    unit: 'per image',
    unitLaborCost: 250,
    laborHours: 5,
    unitMaterialCost: 0,
    quantity: 1,
    optional: false,
    Icon: FaImage,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'simulationVideo',
    name: 'Flight Simulation Video',
    unit: 'per video',
    unitLaborCost: 350,
    laborHours: 7,
    unitMaterialCost: 0,
    quantity: 0,
    optional: true,
    Icon: FaVideo,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
  {
    id: 'complianceDataset',
    name: 'Regulatory Compliance Dataset',
    unit: 'per dataset',
    unitLaborCost: 180,
    laborHours: 3.5,
    unitMaterialCost: 15,
    quantity: 0,
    optional: true,
    Icon: FaDatabase,
    laborMarginPercent: 80,
    materialMarkupPercent: 200,
    discountPercent: 0,
  },
];
